# Generated by Django 4.0.2 on 2022-02-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='Video_file',
            new_name='video_file',
        ),
    ]
